// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvMgt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple iPhone 15",
                            Price = 1200.00m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Samsung Galaxy S24",
                            Price = 1100.00m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Google Pixel 8",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 4,
                            Name = "OnePlus 12",
                            Price = 950.00m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Xiaomi 14 Pro",
                            Price = 875.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
